---
- hosts: manjaro
  remote_user: cody
  become: yes
  tasks:
        - name: update & upgrade
          pacman:
                update_cache: yes
                upgrade: yes

        - name: install
          pacman:
                  name:
                          - bash
                          - nodejs
                          - yarn
                  state: present

